### PR TITLE
Update README.md: --source is now --manifest

### PR DESCRIPTION
**Pull request by tallaxes**

### CODE REVIEW

**Comment by tallaxes** [comment]
I signed it!

**Comment by ahmetb** [comment]
LMK If you can't sign the CLA, I'll make the fix myself.

**Comment by ahmetb** [comment]
I can't find the record of CLA signed for your github account.

**Comment by tallaxes** [comment]
Hmm, had signed it. Just added the GitHub account in there, let's see if this comment pushes it through.

**Pull request merged**
