### PR TITLE
Support form ARM binary

### PR DESCRIPTION
**Pull request by nlamirault**
Add the `arm` architecture to Gox to provide a new binary.
Binaries are named `krew-os_arch`.
Ex:

```
$ unzip -l out/krew.zip
Archive:  out/krew.zip
  Length      Date    Time    Name             
---------  ---------- -----   ----                           
        0  2018-09-24 11:14   out/build/                                                                  
        0  2018-09-24 11:14   out/build/windows/                                                          
        0  2018-09-24 11:14   out/build/windows/commands/
        0  2018-09-24 11:14   out/build/windows/commands/install/
      377  2018-09-24 11:14   out/build/windows/commands/install/plugin.yaml
        0  2018-09-24 11:14   out/build/windows/commands/update/
      261  2018-09-24 11:14   out/build/windows/commands/update/plugin.yaml
        0  2018-09-24 11:14   out/build/windows/commands/upgrade/                                         
      467  2018-09-24 11:14   out/build/windows/commands/upgrade/plugin.yaml                              
        0  2018-09-24 11:14   out/build/windows/commands/search/
      249  2018-09-24 11:14   out/build/windows/commands/search/plugin.yaml
        0  2018-09-24 11:14   out/build/windows/commands/info/
      208  2018-09-24 11:14   out/build/windows/commands/info/plugin.yaml
        0  2018-09-24 11:14   out/build/windows/commands/remove/                   
      201  2018-09-24 11:14   out/build/windows/commands/remove/plugin.yaml
        0  2018-09-24 11:14   out/build/windows/commands/list/
      194  2018-09-24 11:14   out/build/windows/commands/list/plugin.yaml
     3093  2018-09-24 11:14   out/build/windows/plugin.yaml   
 13324638  2018-09-24 11:14   out/build/krew-linux_arm    
 15171744  2018-09-24 11:14   out/build/krew-linux_amd64
 14840800  2018-09-24 11:14   out/build/krew-darwin_amd64
        0  2018-09-24 11:14   out/build/unix/                                                   
        0  2018-09-24 11:14   out/build/unix/commands/                                          
        0  2018-09-24 11:14   out/build/unix/commands/install/                                                                                                                                                     
      373  2018-09-24 11:14   out/build/unix/commands/install/plugin.yaml
        0  2018-09-24 11:14   out/build/unix/commands/update/           
      257  2018-09-24 11:14   out/build/unix/commands/update/plugin.yaml
        0  2018-09-24 11:14   out/build/unix/commands/upgrade/
      463  2018-09-24 11:14   out/build/unix/commands/upgrade/plugin.yaml
        0  2018-09-24 11:14   out/build/unix/commands/search/
      245  2018-09-24 11:14   out/build/unix/commands/search/plugin.yaml
        0  2018-09-24 11:14   out/build/unix/commands/info/
      204  2018-09-24 11:14   out/build/unix/commands/info/plugin.yaml
        0  2018-09-24 11:14   out/build/unix/commands/remove/
      197  2018-09-24 11:14   out/build/unix/commands/remove/plugin.yaml
        0  2018-09-24 11:14   out/build/unix/commands/list/                                               
      190  2018-09-24 11:14   out/build/unix/commands/list/plugin.yaml                                    
     3053  2018-09-24 11:14   out/build/unix/plugin.yaml
 14782464  2018-09-24 11:14   out/build/krew-windows_amd64.exe
```

Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

### CODE REVIEW

**Comment by ahmetb** [comment]
Sorry for the obvious question but are you using krew on arm platforms? What’s your use case?

We nearly have no plugins (other than the ones written in bash scripts) that’s supported on arm.

**Comment by ahmetb** [comment]
@nlamirault 

1. As I commented above, can you please explain your use case for running krew in arm platforms?
2. What GOARM (v6,v7,v8?) should this be built with? Right now it probably defaults to armv6 since you don't specify.

A binary release will be available with probably v0.2 earliest, which could be a month out at least.

**Comment by nlamirault** [comment]
i use the kubectl on an ARM64 Kubernetes cluster (Rocket64 for the master, RPI3 for the nodes)

**Comment by ahmetb** [comment]
@nlamirault sounds good. can you please update `.travis.yml` file to include the renamed binary files + the new binary? I'm adding the new platform installation to #33.

**Comment by ahmetb** [comment]
I'll get this in and patch krew.yaml after #71 is fixed.

**Pull request merged**
