### PR TITLE
readme: add demo GIF

### PR DESCRIPTION
**Pull request by ahmetb**
/cc @lbb

### CODE REVIEW

**Comment by ahmetb** [comment]
/hold

Shame on Github, it doesn't play animated SVGs. 🤷‍♂️

**Comment by lbb** [comment]
I would like to not have annimated gifs, on Chrome on a MBP the CPU usage
is 100%. We should use gif's.

**Comment by ahmetb** [comment]
Do you know an easy way to convert this animated SVG to GIF?

**Comment by lbb** [comment]
Do you have the `.cast` file? We don't need the window border.
BTW, the `.svg` file is playing on my browser but is overutilizing my CPU.

**Comment by ahmetb** [comment]
> Do you have the .cast file? We don't need the window border.

I don't have it.


> BTW, the .svg file is playing on my browser but is overutilizing my CPU.

I am not planning to keep this svg. I see the cpu load too.

**Pull request closed without merging**
