### PR TITLE
docs: add plugin naming guide

### PR DESCRIPTION
**Pull request by ahmetb**
This is to be used/enforced in krew index and document best practices for the
plugin dev community.

### CODE REVIEW

**Comment by bacongobbler** [comment]
would this document be better off in the plugin KEP? Seems a lot of this has more to do with plugin naming issues, less so with krew.

**Comment by bacongobbler** [comment]
I was referring to [the kubectl doc on plugins](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/), sorry, not the KEP for krew.

**Comment by ahmetb** [comment]
I am okay with having it somewhere in the community (i.e. `kubernetes/community` repo has similar stuff).

But I'm not sure if it belongs to the official Kubernetes documentation on plugins.  Simply because kubernetes documentation doesn't offer naming guides to anything (like extensions, CRDs, resource naming for deployment/pod etc) and right now the only entity that accepts plugins is the `krew-index` repo.

So I don't think there's a community position on suggesting or enforcing these names yet, even though these are good practices to follow.

I'm also not sure if everyone agrees with these. We're hoping to enforce it in the `krew-index` repo ASAP, as the naming has already sparkled a lot of debates in almost every PR we got so far.

**Comment by bacongobbler** [comment]
fair enough!

**Comment by ahmetb** [comment]
@bacongobbler Happy to revisit this and move it out of this repo if someone shepherds this in the community/sig-cli.

**Pull request merged**
