### PR TITLE
Migrate to pkg/errors for error wrapping

### LINKED ISSUE #73: Migrate to pkg/errors
We should migrate to http://github.com/pkg/errors sometime. We have a lot of error message consistencies such as:

- `something bad happened, err: %v`
- `something bad happened, err=%+v`
- `something bad happened: %v`

This would involve:

1. Standardize wrapping errors.
2. Format errors with `%+v` where appropriate to print the stack trace.

### PR DESCRIPTION
**Pull request by ahmetb**
Could not resist the temptation. I hope I didn't miss anything. Right now
we don't get stack traces (probably because cobra does not use %+v for printing).

Ran `dep ensure -add github.com/pkg/errors` which resulted in some vendor/ updates.

Fixes #73.

### CODE REVIEW

**Comment by ahmetb** [comment]
I added a `[Pre]RunE` interceptor that would print stack traces:

```
func withStackTrace(f func(*cobra.Command, []string) error) func(*cobra.Command, []string) error {
	return func(cmd *cobra.Command, args []string) error {
		if err := f(cmd, args); err != nil {
			return fmt.Errorf("ERROR=%+v", err)
		}
		return nil
	}
}
```

Rest assured it looks terrible:

```
 krew install foo
Updated index
F1008 12:23:59.894161   97961 root.go:51] ERROR=open /Users/ahmetb/.krew/index/plugins/foo.yaml: no such file or directory
failed to load plugin "foo" from index
github.com/GoogleContainerTools/krew/cmd/krew/cmd.init.1.func1
	/Users/ahmetb/workspace/gopath-krew/src/github.com/GoogleContainerTools/krew/cmd/krew/cmd/install.go:70
github.com/GoogleContainerTools/krew/cmd/krew/cmd.withStackTrace.func1
	/Users/ahmetb/workspace/gopath-krew/src/github.com/GoogleContainerTools/krew/cmd/krew/cmd/root.go:113
github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/ahmetb/workspace/gopath-krew/src/github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra/command.go:762
github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/Users/ahmetb/workspace/gopath-krew/src/github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra/command.go:852
github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/ahmetb/workspace/gopath-krew/src/github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra/command.go:800
github.com/GoogleContainerTools/krew/cmd/krew/cmd.Execute
	/Users/ahmetb/workspace/gopath-krew/src/github.com/GoogleContainerTools/krew/cmd/krew/cmd/root.go:50
main.main
	/Users/ahmetb/workspace/gopath-krew/src/github.com/GoogleContainerTools/krew/cmd/krew/main.go:23
runtime.main
	/Users/ahmetb/.homebrew/Cellar/go/1.11.1/libexec/src/runtime/proc.go:201
runtime.goexit
	/Users/ahmetb/.homebrew/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333
```

Maybe we can consider enabling stack traces later (through -v or something).

**Comment by ahmetb** [comment]
@lbb I'll send a separate CL once I figure out how to read the glog -v flag. :p
I'll merge this if this looks good to you.

**Comment by lbb** [comment]
LGTM

**Pull request merged**
